spring.application.name=Filmorate
server.port=8080

logging.file.path=./logs/
logging.logback.rollingpolicy.file-name-pattern=./logs/spring.%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=50MB
logging.logback.rollingpolicy.clean-history-on-start=true
spring.output.ansi.enabled=ALWAYS