spring.application.name=Filmorate
server.port=8080

logging.file.path=./logs/
logging.logback.rollingpolicy.file-name-pattern=./logs/spring.%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=50MB
logging.logback.rollingpolicy.clean-history-on-start=true
spring.output.ansi.enabled=ALWAYS

logging.level.ru.yandex.practicum.filmorate=DEBUG
logging.level.org.zalando.logbook=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

spring.sql.init.mode=always
#spring.datasource.url=jdbc:h2:file:./db/filmorate
spring.datasource.url=jdbc:h2:mem:filmorate
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.h2.console.enabled=true